<?php
// database/seed_50_medicines.php - 50 Varieties Medicine Database Seeder & Backend Connector

require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../config/database.php';

echo "====================================================================\n";
echo " VATSALYA HOSPITAL PHARMACY — 50 MEDICINE VARIETIES SEEDER\n";
echo "====================================================================\n\n";

try {
    $pdo->beginTransaction();

    $adminUserId = 1;

    // 1. Ensure Suppliers exist
    echo "[1/4] Checking Suppliers...\n";
    $suppliers = [
        ['SUP-001', 'Sun Pharma Distributors', '27AAACS1234A1Z5', '9820012345', 'orders@sunpharma-dist.com', 'Mumbai', 'Maharashtra', '30 Days Net', 'MH-TZ-123456'],
        ['SUP-002', 'Cipla Healthcare Logistics', '27AABCC5678B1Z2', '9820054321', 'supply@ciplalogistics.com', 'Pune', 'Maharashtra', '15 Days Net', 'MH-PUN-789012'],
        ['SUP-003', 'Mankind MediSupply Agency', '27AABCM9012C1Z9', '9820098765', 'contact@mankindagency.in', 'Nagpur', 'Maharashtra', 'Immediate / COD', 'MH-NGP-345678'],
        ['SUP-004', 'Alkem & Abbott Regional Depot', '27AABCA3456D1Z1', '9820077889', 'depot@alkem-abbott.in', 'Thane', 'Maharashtra', '30 Days Net', 'MH-THN-901234']
    ];

    $supIds = [];
    $supStmt = $pdo->prepare("
        INSERT INTO pharmacy_suppliers (supplier_code, supplier_name, gstin, phone, email, city, state, payment_terms, drug_licence_no, status, created_by, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'Active', ?, NOW(), NOW())
        ON DUPLICATE KEY UPDATE supplier_id = LAST_INSERT_ID(supplier_id), supplier_name = VALUES(supplier_name)
    ");
    foreach ($suppliers as $s) {
        $supStmt->execute([$s[0], $s[1], $s[2], $s[3], $s[4], $s[5], $s[6], $s[7], $s[8], $adminUserId]);
        $supIds[$s[0]] = (int)$pdo->lastInsertId();
    }
    echo "  ✓ " . count($suppliers) . " suppliers verified.\n";

    // 2. Mark temporary test rows as Inactive instead of hard deleting
    $pdo->exec("UPDATE medicines SET status = 'Inactive' WHERE medicine_name LIKE 'Direct %' OR medicine_name LIKE 'Ggfgdgd%'");

    // 3. Define 50 Clinical Varieties of Medicines
    echo "[2/4] Preparing 50 distinct varieties of medicines...\n";
    $catalog50 = [
        // 1-10: Analgesics, Antipyretics, Antibiotics, Gastro
        [
            'name' => 'Dolo 650mg Tablet',
            'generic' => 'Paracetamol',
            'composition' => 'Paracetamol 650mg',
            'strength' => '650mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Dolo',
            'category' => 'Antipyretic / Analgesic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'A1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'General',
            'mfg' => 'Micro Labs Ltd',
            'hsn' => '30049060',
            'barcode' => '890100100001',
            'gst' => 12.00,
            'mrp' => 33.00,
            'purchase' => 20.00,
            'stock' => 500,
            'batch_no' => 'DLO-2401',
            'expiry' => '2027-12-31',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Augmentin 625 Duo Tablet',
            'generic' => 'Amoxicillin + Clavulanic Acid',
            'composition' => 'Amoxicillin 500mg + Clavulanic Acid 125mg',
            'strength' => '625mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Augmentin',
            'category' => 'Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A2-05',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 05',
            'schedule' => 'Schedule H',
            'mfg' => 'GlaxoSmithKline Pharmaceuticals',
            'hsn' => '30041000',
            'barcode' => '890100100002',
            'gst' => 12.00,
            'mrp' => 220.00,
            'purchase' => 155.00,
            'stock' => 350,
            'batch_no' => 'AUG-9912',
            'expiry' => '2027-08-30',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Pan 40 Tablet',
            'generic' => 'Pantoprazole',
            'composition' => 'Pantoprazole Gastro-resistant 40mg',
            'strength' => '40mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Pan',
            'category' => 'Antacid / PPI',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'B1-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Alkem Laboratories Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100003',
            'gst' => 12.00,
            'mrp' => 155.00,
            'purchase' => 95.00,
            'stock' => 400,
            'batch_no' => 'PAN-8821',
            'expiry' => '2027-10-15',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Azee 500 Tablet',
            'generic' => 'Azithromycin',
            'composition' => 'Azithromycin 500mg',
            'strength' => '500mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Azee',
            'category' => 'Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '5 Tablets',
            'rack' => 'B2-02',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Cipla Ltd',
            'hsn' => '30042010',
            'barcode' => '890100100004',
            'gst' => 12.00,
            'mrp' => 130.00,
            'purchase' => 85.00,
            'stock' => 250,
            'batch_no' => 'AZ-5542',
            'expiry' => '2027-05-20',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Ascoril-D Plus Syrup 100ml',
            'generic' => 'Dextromethorphan + Phenylephrine',
            'composition' => 'Dextromethorphan HBr 10mg + Phenylephrine 5mg / 5ml',
            'strength' => '100ml',
            'dosage_form' => 'Syrup',
            'brand' => 'Ascoril-D',
            'category' => 'Cough Syrup',
            'unit' => 'Bottle',
            'pack_size' => '100 ml Bottle',
            'rack' => 'C1-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'Schedule H',
            'mfg' => 'Glenmark Pharmaceuticals',
            'hsn' => '30049099',
            'barcode' => '890100100005',
            'gst' => 12.00,
            'mrp' => 125.00,
            'purchase' => 80.00,
            'stock' => 150,
            'batch_no' => 'ASC-1102',
            'expiry' => '2027-04-10',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Monocef 1g Injection',
            'generic' => 'Ceftriaxone Sodium',
            'composition' => 'Ceftriaxone 1000mg with sterile water',
            'strength' => '1000mg',
            'dosage_form' => 'Injection',
            'brand' => 'Monocef',
            'category' => 'Antibiotic Injection',
            'unit' => 'Vial',
            'pack_size' => '1 Vial',
            'rack' => 'INJ-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'Aristo Pharmaceuticals',
            'hsn' => '30042090',
            'barcode' => '890100100006',
            'gst' => 12.00,
            'mrp' => 65.00,
            'purchase' => 42.00,
            'stock' => 200,
            'batch_no' => 'MON-3321',
            'expiry' => '2027-09-15',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Normal Saline 0.9% IV 500ml',
            'generic' => 'Sodium Chloride IV Infusion',
            'composition' => 'Sodium Chloride 0.9% w/v',
            'strength' => '500ml',
            'dosage_form' => 'IV Infusion',
            'brand' => 'NS IV',
            'category' => 'IV Fluid',
            'unit' => 'Bottle',
            'pack_size' => '500 ml Bottle',
            'rack' => 'IV-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'General',
            'mfg' => 'Baxter Healthcare Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100007',
            'gst' => 12.00,
            'mrp' => 48.00,
            'purchase' => 28.00,
            'stock' => 300,
            'batch_no' => 'NS-7730',
            'expiry' => '2027-11-30',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Lantus Solostar 100IU/ml',
            'generic' => 'Insulin Glargine',
            'composition' => 'Insulin Glargine rDNA origin 100IU/ml',
            'strength' => '100 IU/ml',
            'dosage_form' => 'Pre-filled Pen',
            'brand' => 'Lantus',
            'category' => 'Antidiabetic / Insulin',
            'unit' => 'Pen',
            'pack_size' => '3 ml Pen',
            'rack' => 'FRIDGE-1',
            'shelf' => 'Cold Shelf A',
            'box' => 'Bin 01',
            'schedule' => 'Schedule G',
            'mfg' => 'Sanofi India Ltd',
            'hsn' => '30043110',
            'barcode' => '890100100008',
            'gst' => 5.00,
            'mrp' => 680.00,
            'purchase' => 510.00,
            'stock' => 60,
            'batch_no' => 'LAN-4419',
            'expiry' => '2027-03-31',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Zerodol-SP Tablet',
            'generic' => 'Aceclofenac + Paracetamol + Serratiopeptidase',
            'composition' => 'Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg',
            'strength' => '100+325+15mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Zerodol',
            'category' => 'Analgesic / Anti-inflammatory',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A1-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Ipca Laboratories Ltd',
            'hsn' => '30049060',
            'barcode' => '890100100009',
            'gst' => 12.00,
            'mrp' => 118.00,
            'purchase' => 76.00,
            'stock' => 350,
            'batch_no' => 'ZRD-9021',
            'expiry' => '2027-11-20',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Combiflam Tablet',
            'generic' => 'Ibuprofen + Paracetamol',
            'composition' => 'Ibuprofen 400mg + Paracetamol 325mg',
            'strength' => '400+325mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Combiflam',
            'category' => 'Analgesic / Antipyretic',
            'unit' => 'Strip',
            'pack_size' => '20 Tablets',
            'rack' => 'A1-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'General',
            'mfg' => 'Sanofi India Ltd',
            'hsn' => '30049060',
            'barcode' => '890100100010',
            'gst' => 12.00,
            'mrp' => 45.00,
            'purchase' => 28.00,
            'stock' => 500,
            'batch_no' => 'CMB-7714',
            'expiry' => '2027-08-15',
            'sup_code' => 'SUP-001'
        ],

        // 11-20: Analgesics, Antibiotics, Antispasmodics, PPI
        [
            'name' => 'Ultracet Tablet',
            'generic' => 'Tramadol Hydrochloride + Paracetamol',
            'composition' => 'Tramadol HCl 37.5mg + Paracetamol 325mg',
            'strength' => '37.5+325mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Ultracet',
            'category' => 'Analgesic (Schedule H1)',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'A1-05',
            'shelf' => 'Lock A',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H1',
            'mfg' => 'Johnson & Johnson Ltd',
            'hsn' => '30049060',
            'barcode' => '890100100011',
            'gst' => 12.00,
            'mrp' => 240.00,
            'purchase' => 165.00,
            'stock' => 120,
            'batch_no' => 'ULT-3321',
            'expiry' => '2027-06-30',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Meftal-Spas Tablet',
            'generic' => 'Mefenamic Acid + Dicyclomine',
            'composition' => 'Mefenamic Acid 250mg + Dicyclomine HCl 10mg',
            'strength' => '250+10mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Meftal-Spas',
            'category' => 'Antispasmodic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A1-06',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 06',
            'schedule' => 'Schedule H',
            'mfg' => 'Blue Cross Laboratories',
            'hsn' => '30049099',
            'barcode' => '890100100012',
            'gst' => 12.00,
            'mrp' => 52.00,
            'purchase' => 32.00,
            'stock' => 280,
            'batch_no' => 'MFT-6651',
            'expiry' => '2027-09-10',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Taxim-O 200 Tablet',
            'generic' => 'Cefixime',
            'composition' => 'Cefixime 200mg',
            'strength' => '200mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Taxim-O',
            'category' => 'Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A2-01',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H1',
            'mfg' => 'Alkem Laboratories Ltd',
            'hsn' => '30042090',
            'barcode' => '890100100013',
            'gst' => 12.00,
            'mrp' => 110.00,
            'purchase' => 70.00,
            'stock' => 300,
            'batch_no' => 'TXM-8812',
            'expiry' => '2027-07-25',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Clavam 625 Tablet',
            'generic' => 'Amoxicillin + Clavulanic Acid',
            'composition' => 'Amoxicillin 500mg + Potassium Clavulanate 125mg',
            'strength' => '625mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Clavam',
            'category' => 'Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A2-02',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Alkem Laboratories Ltd',
            'hsn' => '30041000',
            'barcode' => '890100100014',
            'gst' => 12.00,
            'mrp' => 215.00,
            'purchase' => 148.00,
            'stock' => 220,
            'batch_no' => 'CLV-4411',
            'expiry' => '2027-10-31',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Cifran 500 Tablet',
            'generic' => 'Ciprofloxacin',
            'composition' => 'Ciprofloxacin Hydrochloride 500mg',
            'strength' => '500mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Cifran',
            'category' => 'Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'A2-03',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Sun Pharma Industries',
            'hsn' => '30042090',
            'barcode' => '890100100015',
            'gst' => 12.00,
            'mrp' => 46.00,
            'purchase' => 28.00,
            'stock' => 260,
            'batch_no' => 'CFR-1903',
            'expiry' => '2027-05-18',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Metrogyl 400 Tablet',
            'generic' => 'Metronidazole',
            'composition' => 'Metronidazole 400mg',
            'strength' => '400mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Metrogyl',
            'category' => 'Antiamoebic / Antibiotic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'A2-04',
            'shelf' => 'Shelf 2',
            'box' => 'Bin 04',
            'schedule' => 'Schedule H',
            'mfg' => 'J.B. Chemicals & Pharmaceuticals',
            'hsn' => '30049099',
            'barcode' => '890100100016',
            'gst' => 12.00,
            'mrp' => 24.50,
            'purchase' => 14.00,
            'stock' => 450,
            'batch_no' => 'MTG-5510',
            'expiry' => '2027-11-15',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Omez 20 Capsule',
            'generic' => 'Omeprazole',
            'composition' => 'Omeprazole Gastro-resistant 20mg',
            'strength' => '20mg',
            'dosage_form' => 'Capsule',
            'brand' => 'Omez',
            'category' => 'Antacid / PPI',
            'unit' => 'Strip',
            'pack_size' => '20 Capsules',
            'rack' => 'B1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'Dr. Reddy\'s Laboratories',
            'hsn' => '30049099',
            'barcode' => '890100100017',
            'gst' => 12.00,
            'mrp' => 64.00,
            'purchase' => 38.00,
            'stock' => 380,
            'batch_no' => 'OMZ-8891',
            'expiry' => '2027-12-10',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Razo 20 Tablet',
            'generic' => 'Rabeprazole Sodium',
            'composition' => 'Rabeprazole Sodium 20mg',
            'strength' => '20mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Razo',
            'category' => 'Antacid / PPI',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'B1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Dr. Reddy\'s Laboratories',
            'hsn' => '30049099',
            'barcode' => '890100100018',
            'gst' => 12.00,
            'mrp' => 145.00,
            'purchase' => 92.00,
            'stock' => 290,
            'batch_no' => 'RZO-3329',
            'expiry' => '2027-08-20',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Ondem 4 Tablet',
            'generic' => 'Ondansetron',
            'composition' => 'Ondansetron Hydrochloride 4mg',
            'strength' => '4mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Ondem',
            'category' => 'Antiemetic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'B1-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'Schedule H',
            'mfg' => 'Alkem Laboratories Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100019',
            'gst' => 12.00,
            'mrp' => 58.00,
            'purchase' => 35.00,
            'stock' => 310,
            'batch_no' => 'OND-7762',
            'expiry' => '2027-10-05',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Digene Gel Mint 200ml',
            'generic' => 'Magnesium + Aluminium Hydroxide + Simethicone',
            'composition' => 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
            'strength' => '200ml',
            'dosage_form' => 'Syrup',
            'brand' => 'Digene',
            'category' => 'Antacid Liquid',
            'unit' => 'Bottle',
            'pack_size' => '200 ml Bottle',
            'rack' => 'B1-05',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 05',
            'schedule' => 'General',
            'mfg' => 'Abbott India Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100020',
            'gst' => 12.00,
            'mrp' => 155.00,
            'purchase' => 105.00,
            'stock' => 110,
            'batch_no' => 'DGN-1004',
            'expiry' => '2027-06-15',
            'sup_code' => 'SUP-004'
        ],

        // 21-30: Cardiovascular, Respiratory, Antidiabetic
        [
            'name' => 'Telma 40 Tablet',
            'generic' => 'Telmisartan',
            'composition' => 'Telmisartan 40mg',
            'strength' => '40mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Telma',
            'category' => 'Antihypertensive',
            'unit' => 'Strip',
            'pack_size' => '30 Tablets',
            'rack' => 'D1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'Glenmark Pharmaceuticals',
            'hsn' => '30049099',
            'barcode' => '890100100021',
            'gst' => 12.00,
            'mrp' => 220.00,
            'purchase' => 140.00,
            'stock' => 340,
            'batch_no' => 'TLM-4402',
            'expiry' => '2027-11-28',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Amlong 5 Tablet',
            'generic' => 'Amlodipine Besylate',
            'composition' => 'Amlodipine Besylate 5mg',
            'strength' => '5mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Amlong',
            'category' => 'Antihypertensive',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'D1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Micro Labs Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100022',
            'gst' => 12.00,
            'mrp' => 44.00,
            'purchase' => 26.00,
            'stock' => 400,
            'batch_no' => 'AML-8921',
            'expiry' => '2027-09-30',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Atorva 20 Tablet',
            'generic' => 'Atorvastatin',
            'composition' => 'Atorvastatin Calcium 20mg',
            'strength' => '20mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Atorva',
            'category' => 'Lipid Lowering / Statin',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'D1-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Zydus Cadila Healthcare',
            'hsn' => '30049099',
            'barcode' => '890100100023',
            'gst' => 12.00,
            'mrp' => 225.00,
            'purchase' => 150.00,
            'stock' => 250,
            'batch_no' => 'ATR-6623',
            'expiry' => '2027-07-15',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Clopilet 75 Tablet',
            'generic' => 'Clopidogrel',
            'composition' => 'Clopidogrel Bisulphate 75mg',
            'strength' => '75mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Clopilet',
            'category' => 'Antiplatelet',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'D1-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'Schedule H',
            'mfg' => 'Sun Pharma Industries',
            'hsn' => '30049099',
            'barcode' => '890100100024',
            'gst' => 12.00,
            'mrp' => 125.00,
            'purchase' => 78.00,
            'stock' => 210,
            'batch_no' => 'CLP-1109',
            'expiry' => '2027-10-10',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Montek-LC Tablet',
            'generic' => 'Montelukast + Levocetirizine',
            'composition' => 'Montelukast Sodium 10mg + Levocetirizine HCl 5mg',
            'strength' => '10+5mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Montek-LC',
            'category' => 'Antiallergic / Antiasthmatic',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'C1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'Sun Pharma Industries',
            'hsn' => '30049099',
            'barcode' => '890100100025',
            'gst' => 12.00,
            'mrp' => 180.00,
            'purchase' => 110.00,
            'stock' => 320,
            'batch_no' => 'MTK-9981',
            'expiry' => '2027-12-05',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Allegra 120 Tablet',
            'generic' => 'Fexofenadine Hydrochloride',
            'composition' => 'Fexofenadine Hydrochloride 120mg',
            'strength' => '120mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Allegra',
            'category' => 'Antihistamine',
            'unit' => 'Strip',
            'pack_size' => '10 Tablets',
            'rack' => 'C1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'General',
            'mfg' => 'Sanofi India Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100026',
            'gst' => 12.00,
            'mrp' => 198.00,
            'purchase' => 135.00,
            'stock' => 270,
            'batch_no' => 'ALG-3420',
            'expiry' => '2027-09-18',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Asthalin Inhaler 200 MDI',
            'generic' => 'Salbutamol / Albuterol',
            'composition' => 'Salbutamol Sulphate 100mcg per actuation',
            'strength' => '200 MDI',
            'dosage_form' => 'Inhaler',
            'brand' => 'Asthalin',
            'category' => 'Bronchodilator',
            'unit' => 'Canister',
            'pack_size' => '200 Doses',
            'rack' => 'C1-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Cipla Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100027',
            'gst' => 12.00,
            'mrp' => 165.00,
            'purchase' => 115.00,
            'stock' => 85,
            'batch_no' => 'AST-5529',
            'expiry' => '2027-08-30',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Budecort 200 Inhaler',
            'generic' => 'Budesonide',
            'composition' => 'Budesonide 200mcg per actuation',
            'strength' => '200mcg',
            'dosage_form' => 'Inhaler',
            'brand' => 'Budecort',
            'category' => 'Corticosteroid Inhaler',
            'unit' => 'Canister',
            'pack_size' => '200 Doses',
            'rack' => 'C1-05',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 05',
            'schedule' => 'Schedule H',
            'mfg' => 'Cipla Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100028',
            'gst' => 12.00,
            'mrp' => 395.00,
            'purchase' => 280.00,
            'stock' => 60,
            'batch_no' => 'BDC-7718',
            'expiry' => '2027-07-20',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Glycomet-GP 1 Tablet',
            'generic' => 'Metformin + Glimepiride',
            'composition' => 'Metformin Hydrochloride 500mg + Glimepiride 1mg',
            'strength' => '500+1mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Glycomet',
            'category' => 'Antidiabetic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'E1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'USV Private Limited',
            'hsn' => '30049099',
            'barcode' => '890100100029',
            'gst' => 12.00,
            'mrp' => 115.00,
            'purchase' => 74.00,
            'stock' => 390,
            'batch_no' => 'GLY-9901',
            'expiry' => '2027-11-10',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Janumet 50/500 Tablet',
            'generic' => 'Sitagliptin + Metformin',
            'composition' => 'Sitagliptin Phosphate 50mg + Metformin 500mg',
            'strength' => '50+500mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Janumet',
            'category' => 'Antidiabetic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'E1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'MSD Pharmaceuticals',
            'hsn' => '30049099',
            'barcode' => '890100100030',
            'gst' => 12.00,
            'mrp' => 365.00,
            'purchase' => 260.00,
            'stock' => 140,
            'batch_no' => 'JNM-2234',
            'expiry' => '2027-10-30',
            'sup_code' => 'SUP-001'
        ],

        // 31-40: Supplements, Injectables, Topicals, IV Fluids
        [
            'name' => 'Becosules Capsule',
            'generic' => 'B-Complex + Vitamin C',
            'composition' => 'Thiamine + Riboflavin + Niacinamide + Pyridoxine + Calcium Pantothenate + Vitamin B12 + Vitamin C + Folic Acid',
            'strength' => 'Standard',
            'dosage_form' => 'Capsule',
            'brand' => 'Becosules',
            'category' => 'Nutritional Supplement',
            'unit' => 'Strip',
            'pack_size' => '20 Capsules',
            'rack' => 'F1-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'General',
            'mfg' => 'Pfizer Healthcare India',
            'hsn' => '30045090',
            'barcode' => '890100100031',
            'gst' => 12.00,
            'mrp' => 52.00,
            'purchase' => 32.00,
            'stock' => 520,
            'batch_no' => 'BCS-8832',
            'expiry' => '2027-12-15',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Shelcal 500 Tablet',
            'generic' => 'Calcium + Vitamin D3',
            'composition' => 'Elemental Calcium 500mg + Vitamin D3 250 IU',
            'strength' => '500mg+250IU',
            'dosage_form' => 'Tablet',
            'brand' => 'Shelcal',
            'category' => 'Calcium Supplement',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'F1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'General',
            'mfg' => 'Torrent Pharmaceuticals',
            'hsn' => '30045090',
            'barcode' => '890100100032',
            'gst' => 12.00,
            'mrp' => 135.00,
            'purchase' => 88.00,
            'stock' => 410,
            'batch_no' => 'SHL-4491',
            'expiry' => '2027-09-25',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Neurobion Forte Tablet',
            'generic' => 'Vitamin B-Complex + B12',
            'composition' => 'Thiamine 10mg + Riboflavin 10mg + Pyridoxine 3mg + Cyanocobalamin 15mcg + Nicotinamide 45mg',
            'strength' => 'Forte',
            'dosage_form' => 'Tablet',
            'brand' => 'Neurobion',
            'category' => 'Nutritional Supplement',
            'unit' => 'Strip',
            'pack_size' => '30 Tablets',
            'rack' => 'F1-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'General',
            'mfg' => 'Procter & Gamble Health',
            'hsn' => '30045090',
            'barcode' => '890100100033',
            'gst' => 12.00,
            'mrp' => 41.50,
            'purchase' => 26.00,
            'stock' => 480,
            'batch_no' => 'NRB-6602',
            'expiry' => '2027-11-18',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Dynapar AQ Injection 1ml',
            'generic' => 'Diclofenac Sodium',
            'composition' => 'Diclofenac Sodium 75mg/ml aqueous solution',
            'strength' => '75mg/ml',
            'dosage_form' => 'Injection',
            'brand' => 'Dynapar',
            'category' => 'Analgesic Injection',
            'unit' => 'Ampoule',
            'pack_size' => '1 ml Ampoule',
            'rack' => 'INJ-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Troikaa Pharmaceuticals',
            'hsn' => '30049060',
            'barcode' => '890100100034',
            'gst' => 12.00,
            'mrp' => 32.00,
            'purchase' => 19.50,
            'stock' => 200,
            'batch_no' => 'DNP-9011',
            'expiry' => '2027-08-10',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Dexona 2ml Injection',
            'generic' => 'Dexamethasone Sodium Phosphate',
            'composition' => 'Dexamethasone Sodium Phosphate 4mg/ml',
            'strength' => '8mg/2ml',
            'dosage_form' => 'Injection',
            'brand' => 'Dexona',
            'category' => 'Corticosteroid Injection',
            'unit' => 'Vial',
            'pack_size' => '2 ml Vial',
            'rack' => 'INJ-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Zydus Cadila Healthcare',
            'hsn' => '30043200',
            'barcode' => '890100100035',
            'gst' => 12.00,
            'mrp' => 14.50,
            'purchase' => 8.50,
            'stock' => 240,
            'batch_no' => 'DXN-1198',
            'expiry' => '2027-10-15',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Ringer Lactate (RL) IV 500ml',
            'generic' => 'Sodium Lactate Compound IV',
            'composition' => 'Sodium Chloride + Sodium Lactate + Potassium Chloride + Calcium Chloride',
            'strength' => '500ml',
            'dosage_form' => 'IV Infusion',
            'brand' => 'RL Infusion',
            'category' => 'IV Fluid',
            'unit' => 'Bottle',
            'pack_size' => '500 ml Bottle',
            'rack' => 'IV-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'General',
            'mfg' => 'Fresenius Kabi India',
            'hsn' => '30049099',
            'barcode' => '890100100036',
            'gst' => 12.00,
            'mrp' => 55.00,
            'purchase' => 33.00,
            'stock' => 190,
            'batch_no' => 'RL-5520',
            'expiry' => '2027-12-20',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Betadine 10% Ointment 20g',
            'generic' => 'Povidone-Iodine',
            'composition' => 'Povidone Iodine 10% w/w (available iodine 1% w/w)',
            'strength' => '10% w/w',
            'dosage_form' => 'Ointment',
            'brand' => 'Betadine',
            'category' => 'Antiseptic Ointment',
            'unit' => 'Tube',
            'pack_size' => '20 g Tube',
            'rack' => 'TOP-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'General',
            'mfg' => 'Win-Medicare Private Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100037',
            'gst' => 12.00,
            'mrp' => 125.00,
            'purchase' => 82.00,
            'stock' => 150,
            'batch_no' => 'BTD-8824',
            'expiry' => '2027-09-05',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Volini Pain Relief Gel 30g',
            'generic' => 'Diclofenac Diethylamine + Methyl Salicylate',
            'composition' => 'Diclofenac Diethylamine 1.16% + Linseed Oil 3% + Methyl Salicylate 10% + Menthol 5%',
            'strength' => '30g',
            'dosage_form' => 'Gel',
            'brand' => 'Volini',
            'category' => 'Topical Analgesic',
            'unit' => 'Tube',
            'pack_size' => '30 g Tube',
            'rack' => 'TOP-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'General',
            'mfg' => 'Sun Pharma Consumer Healthcare',
            'hsn' => '30049060',
            'barcode' => '890100100038',
            'gst' => 12.00,
            'mrp' => 140.00,
            'purchase' => 95.00,
            'stock' => 135,
            'batch_no' => 'VLN-4421',
            'expiry' => '2027-11-30',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Dextrose 5% (D5) IV 500ml',
            'generic' => 'Dextrose IV Infusion',
            'composition' => 'Dextrose Anhydrous 5% w/v in sterile water for injection',
            'strength' => '5% w/v',
            'dosage_form' => 'IV Infusion',
            'brand' => 'D5 Infusion',
            'category' => 'IV Fluid',
            'unit' => 'Bottle',
            'pack_size' => '500 ml Bottle',
            'rack' => 'IV-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'General',
            'mfg' => 'Baxter Healthcare Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100039',
            'gst' => 12.00,
            'mrp' => 50.00,
            'purchase' => 30.00,
            'stock' => 210,
            'batch_no' => 'D5-3310',
            'expiry' => '2027-10-25',
            'sup_code' => 'SUP-002'
        ],
        [
            'name' => 'Ciplox Eye/Ear Drops 10ml',
            'generic' => 'Ciprofloxacin Ophthalmic Solution',
            'composition' => 'Ciprofloxacin Hydrochloride 0.3% w/v',
            'strength' => '0.3% w/v',
            'dosage_form' => 'Eye/Ear Drops',
            'brand' => 'Ciplox',
            'category' => 'Ophthalmic / Otic',
            'unit' => 'Vial',
            'pack_size' => '10 ml Bottle',
            'rack' => 'DROPS-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Schedule H',
            'mfg' => 'Cipla Ltd',
            'hsn' => '30042090',
            'barcode' => '890100100040',
            'gst' => 12.00,
            'mrp' => 22.00,
            'purchase' => 13.50,
            'stock' => 160,
            'batch_no' => 'CPX-7740',
            'expiry' => '2027-08-12',
            'sup_code' => 'SUP-002'
        ],

        // 41-50: Critical Hospital & Pharmacy Varieties
        [
            'name' => 'Otrivin 0.1% Adult Nasal Spray 10ml',
            'generic' => 'Xylometazoline Hydrochloride',
            'composition' => 'Xylometazoline Hydrochloride 0.1% w/v',
            'strength' => '0.1% w/v',
            'dosage_form' => 'Nasal Spray',
            'brand' => 'Otrivin',
            'category' => 'Nasal Decongestant',
            'unit' => 'Bottle',
            'pack_size' => '10 ml Spray',
            'rack' => 'SPRAY-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'General',
            'mfg' => 'GlaxoSmithKline Consumer',
            'hsn' => '30049099',
            'barcode' => '890100100041',
            'gst' => 12.00,
            'mrp' => 105.00,
            'purchase' => 68.00,
            'stock' => 120,
            'batch_no' => 'OTR-9905',
            'expiry' => '2027-09-30',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Supradyn Daily Tablet',
            'generic' => 'Multivitamins + Minerals + Trace Elements',
            'composition' => 'Vitamin A + B-Complex + C + D3 + E + Zinc + Calcium + Magnesium',
            'strength' => 'Daily Multi',
            'dosage_form' => 'Tablet',
            'brand' => 'Supradyn',
            'category' => 'Nutritional Supplement',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'F1-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'General',
            'mfg' => 'Bayer Pharmaceuticals',
            'hsn' => '30045090',
            'barcode' => '890100100042',
            'gst' => 12.00,
            'mrp' => 62.00,
            'purchase' => 40.00,
            'stock' => 350,
            'batch_no' => 'SPD-3319',
            'expiry' => '2027-11-15',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Ecosprin 75 Tablet',
            'generic' => 'Aspirin / Acetylsalicylic Acid',
            'composition' => 'Aspirin Gastro-resistant 75mg',
            'strength' => '75mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Ecosprin',
            'category' => 'Antiplatelet / Cardiac',
            'unit' => 'Strip',
            'pack_size' => '14 Tablets',
            'rack' => 'D1-05',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 05',
            'schedule' => 'Schedule H',
            'mfg' => 'USV Private Limited',
            'hsn' => '30049060',
            'barcode' => '890100100043',
            'gst' => 12.00,
            'mrp' => 11.50,
            'purchase' => 6.50,
            'stock' => 600,
            'batch_no' => 'ECO-5521',
            'expiry' => '2027-12-31',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Liv 52 DS Tablet',
            'generic' => 'Herbal Hepatoprotective Extract',
            'composition' => 'Himsra (Capparis spinosa) + Kasani (Cichorium intybus) Ayurvedic formulation',
            'strength' => 'Double Strength',
            'dosage_form' => 'Tablet',
            'brand' => 'Liv 52',
            'category' => 'Hepatic / Liver Care',
            'unit' => 'Bottle',
            'pack_size' => '60 Tablets',
            'rack' => 'HERB-01',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 01',
            'schedule' => 'Ayurvedic',
            'mfg' => 'The Himalaya Drug Company',
            'hsn' => '30049011',
            'barcode' => '890100100044',
            'gst' => 12.00,
            'mrp' => 185.00,
            'purchase' => 125.00,
            'stock' => 250,
            'batch_no' => 'LIV-7729',
            'expiry' => '2027-10-20',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Pantocid DSR Capsule',
            'generic' => 'Pantoprazole + Domperidone SR',
            'composition' => 'Pantoprazole Sodium 40mg + Domperidone Sustained Release 30mg',
            'strength' => '40+30mg',
            'dosage_form' => 'Capsule',
            'brand' => 'Pantocid',
            'category' => 'Antacid / Antiemetic',
            'unit' => 'Strip',
            'pack_size' => '15 Capsules',
            'rack' => 'B1-06',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 06',
            'schedule' => 'Schedule H',
            'mfg' => 'Sun Pharma Industries',
            'hsn' => '30049099',
            'barcode' => '890100100045',
            'gst' => 12.00,
            'mrp' => 235.00,
            'purchase' => 155.00,
            'stock' => 300,
            'batch_no' => 'PTC-8810',
            'expiry' => '2027-11-12',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Voveran 50mg Tablet',
            'generic' => 'Diclofenac Sodium',
            'composition' => 'Diclofenac Sodium Enteric Coated 50mg',
            'strength' => '50mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Voveran',
            'category' => 'NSAID / Analgesic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'A1-02',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 02',
            'schedule' => 'Schedule H',
            'mfg' => 'Novartis India Ltd',
            'hsn' => '30049060',
            'barcode' => '890100100046',
            'gst' => 12.00,
            'mrp' => 85.00,
            'purchase' => 52.00,
            'stock' => 320,
            'batch_no' => 'VOV-3341',
            'expiry' => '2027-08-18',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Calpol 500mg Tablet',
            'generic' => 'Paracetamol',
            'composition' => 'Paracetamol BP 500mg',
            'strength' => '500mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Calpol',
            'category' => 'Antipyretic / Analgesic',
            'unit' => 'Strip',
            'pack_size' => '15 Tablets',
            'rack' => 'A1-07',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 07',
            'schedule' => 'General',
            'mfg' => 'GlaxoSmithKline Pharmaceuticals',
            'hsn' => '30049060',
            'barcode' => '890100100047',
            'gst' => 12.00,
            'mrp' => 21.00,
            'purchase' => 12.50,
            'stock' => 450,
            'batch_no' => 'CLP-6612',
            'expiry' => '2027-10-31',
            'sup_code' => 'SUP-001'
        ],
        [
            'name' => 'Kenacort 40mg Injection',
            'generic' => 'Triamcinolone Acetonide',
            'composition' => 'Triamcinolone Acetonide sterile aqueous suspension 40mg/ml',
            'strength' => '40mg/ml',
            'dosage_form' => 'Injection',
            'brand' => 'Kenacort',
            'category' => 'Corticosteroid Injection',
            'unit' => 'Vial',
            'pack_size' => '1 ml Vial',
            'rack' => 'INJ-04',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 04',
            'schedule' => 'Schedule H',
            'mfg' => 'Abbott Healthcare Pvt Ltd',
            'hsn' => '30043200',
            'barcode' => '890100100048',
            'gst' => 12.00,
            'mrp' => 145.00,
            'purchase' => 98.00,
            'stock' => 90,
            'batch_no' => 'KNC-9915',
            'expiry' => '2027-06-25',
            'sup_code' => 'SUP-004'
        ],
        [
            'name' => 'Deriphyllin Retard 150 Tablet',
            'generic' => 'Theophylline + Etofylline',
            'composition' => 'Theophylline 115mg + Etofylline 35mg Prolonged Release',
            'strength' => '150mg',
            'dosage_form' => 'Tablet',
            'brand' => 'Deriphyllin',
            'category' => 'Respiratory / Bronchodilator',
            'unit' => 'Strip',
            'pack_size' => '30 Tablets',
            'rack' => 'C1-06',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 06',
            'schedule' => 'Schedule H',
            'mfg' => 'Zydus Healthcare Ltd',
            'hsn' => '30049099',
            'barcode' => '890100100049',
            'gst' => 12.00,
            'mrp' => 38.00,
            'purchase' => 22.00,
            'stock' => 310,
            'batch_no' => 'DRP-4410',
            'expiry' => '2027-09-12',
            'sup_code' => 'SUP-003'
        ],
        [
            'name' => 'Candid-B Cream 20g',
            'generic' => 'Clotrimazole + Beclomethasone Dipropionate',
            'composition' => 'Clotrimazole 1.0% w/w + Beclomethasone Dipropionate 0.025% w/w',
            'strength' => '20g',
            'dosage_form' => 'Cream',
            'brand' => 'Candid-B',
            'category' => 'Antifungal / Anti-inflammatory',
            'unit' => 'Tube',
            'pack_size' => '20 g Tube',
            'rack' => 'TOP-03',
            'shelf' => 'Shelf 1',
            'box' => 'Bin 03',
            'schedule' => 'Schedule H',
            'mfg' => 'Glenmark Pharmaceuticals',
            'hsn' => '30042090',
            'barcode' => '890100100050',
            'gst' => 12.00,
            'mrp' => 165.00,
            'purchase' => 108.00,
            'stock' => 140,
            'batch_no' => 'CND-2218',
            'expiry' => '2027-11-20',
            'sup_code' => 'SUP-003'
        ]
    ];

    echo "  ✓ Defined " . count($catalog50) . " rich varieties.\n";

    // 4. Prepared Statements
    echo "[3/4] Inserting/Updating Medicines, Batches, and Stock Ledger...\n";

    $checkMedStmt = $pdo->prepare("SELECT medicine_id FROM medicines WHERE barcode = ? OR medicine_name = ? LIMIT 1");

    $insertMedStmt = $pdo->prepare("
        INSERT INTO medicines (
            medicine_name, generic_name, composition, strength, dosage_form, brand_name,
            category, unit, pack_size, rack_location, shelf, box_bin, schedule_type,
            manufacturer, hsn_code, gst_percent, price, purchase_price, stock_quantity,
            reorder_level, min_stock, max_stock, reorder_qty, barcode, status, created_by,
            created_at, updated_at
        ) VALUES (
            ?, ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?, ?,
            20, 10, 1000, 50, ?, 'Active', ?,
            NOW(), NOW()
        )
    ");

    $updateMedStmt = $pdo->prepare("
        UPDATE medicines SET
            medicine_name = ?, generic_name = ?, composition = ?, strength = ?, dosage_form = ?,
            brand_name = ?, category = ?, unit = ?, pack_size = ?, rack_location = ?,
            shelf = ?, box_bin = ?, schedule_type = ?, manufacturer = ?, hsn_code = ?,
            gst_percent = ?, price = ?, purchase_price = ?, stock_quantity = ?, barcode = ?,
            status = 'Active', updated_at = NOW()
        WHERE medicine_id = ?
    ");

    $batchStmt = $pdo->prepare("
        INSERT INTO medicine_batches (
            medicine_id, batch_number, manufacturing_date, expiry_date, purchase_price,
            mrp, sale_price, quantity_received, quantity_available, supplier_id,
            shelf_location, status, created_at, updated_at
        ) VALUES (
            ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?,
            ?, 'Active', NOW(), NOW()
        )
        ON DUPLICATE KEY UPDATE
            batch_id = LAST_INSERT_ID(batch_id),
            quantity_available = VALUES(quantity_available),
            expiry_date = VALUES(expiry_date),
            mrp = VALUES(mrp),
            purchase_price = VALUES(purchase_price),
            status = 'Active'
    ");

    $ledgerStmt = $pdo->prepare("
        INSERT INTO pharmacy_stock_ledger (
            medicine_id, batch_id, transaction_type, reference_type, reference_no,
            quantity_change, balance_before, balance_after, unit_cost, unit_price,
            reason, created_by, created_at
        ) VALUES (
            ?, ?, 'OPENING_STOCK', 'VARIETIES_SEED_50', 'SEED-50-2026',
            ?, 0, ?, ?, ?,
            'Initial 50 Varieties Catalog and Stock Synchronization', ?, NOW()
        )
    ");

    $countProcessed = 0;
    foreach ($catalog50 as $item) {
        $checkMedStmt->execute([$item['barcode'], $item['name']]);
        $existingId = $checkMedStmt->fetchColumn();

        if ($existingId) {
            $medId = (int)$existingId;
            $updateMedStmt->execute([
                $item['name'], $item['generic'], $item['composition'], $item['strength'], $item['dosage_form'],
                $item['brand'], $item['category'], $item['unit'], $item['pack_size'], $item['rack'],
                $item['shelf'], $item['box'], $item['schedule'], $item['mfg'], $item['hsn'],
                $item['gst'], $item['mrp'], $item['purchase'], $item['stock'], $item['barcode'],
                $medId
            ]);
        } else {
            $insertMedStmt->execute([
                $item['name'], $item['generic'], $item['composition'], $item['strength'], $item['dosage_form'],
                $item['brand'], $item['category'], $item['unit'], $item['pack_size'], $item['rack'],
                $item['shelf'], $item['box'], $item['schedule'], $item['mfg'], $item['hsn'],
                $item['gst'], $item['mrp'], $item['purchase'], $item['stock'], $item['barcode'],
                $adminUserId
            ]);
            $medId = (int)$pdo->lastInsertId();
        }

        $supId = $supIds[$item['sup_code']] ?? $supIds['SUP-001'];
        $mfgDate = date('Y-m-01', strtotime('-3 months'));

        $batchStmt->execute([
            $medId, $item['batch_no'], $mfgDate, $item['expiry'], $item['purchase'],
            $item['mrp'], $item['mrp'], $item['stock'] + 50, $item['stock'], $supId,
            $item['rack']
        ]);
        $batchId = (int)$pdo->lastInsertId();

        // Check if ledger entry exists
        $hasLedger = $pdo->prepare("SELECT COUNT(*) FROM pharmacy_stock_ledger WHERE medicine_id = ? AND batch_id = ?");
        $hasLedger->execute([$medId, $batchId]);
        if ($hasLedger->fetchColumn() == 0) {
            $ledgerStmt->execute([
                $medId, $batchId, $item['stock'], $item['stock'], $item['purchase'], $item['mrp'], $adminUserId
            ]);
        }

        $countProcessed++;
    }

    $pdo->commit();
    echo "  ✓ Successfully seeded & synced $countProcessed medicines with batch inventory.\n";

    // Verification check
    echo "\n[4/4] Verifying Final Database Statistics...\n";
    $finalMeds = $pdo->query("SELECT COUNT(*) FROM medicines WHERE status = 'Active'")->fetchColumn();
    $finalBatches = $pdo->query("SELECT COUNT(*) FROM medicine_batches WHERE status = 'Active'")->fetchColumn();
    $totalStock = $pdo->query("SELECT SUM(quantity_available) FROM medicine_batches WHERE status = 'Active'")->fetchColumn();

    echo "  • Total Active Medicines in Database: $finalMeds\n";
    echo "  • Total Active Batches in Database:   $finalBatches\n";
    echo "  • Total Unit Stock across Inventory: $totalStock\n";

    echo "\n====================================================================\n";
    echo " DATABASE AND BACKEND SYNCHRONIZATION COMPLETED SUCCESSFULLY!\n";
    echo "====================================================================\n";

} catch (Exception $e) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }
    echo "\n❌ ERROR: " . $e->getMessage() . "\n";
    exit(1);
}
